### ISSUE TITLE
No Record for flightnumber

### ISSUE THREAD

**Issue by tobyweston** [alltonp/flakeless#5]
Upgrading from 0.0.129 to 0.0.166 produces the following for all tests.

Thought I'd post it in case it rings any bells.

```scala
Starting ChromeDriver 2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7) on port 11901
Only local connections are allowed.
Jun 12, 2018 8:31:02 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

No Record for flightnumber: 1
java.lang.RuntimeException: No Record for flightnumber: 1
	at im.mange.flakeless.innards.FlightDataRecorder.$anonfun$data$1(FlightDataRecorder.scala:36)
	at scala.Option.getOrElse(Option.scala:121)
	at im.mange.flakeless.innards.FlightDataRecorder.data(FlightDataRecorder.scala:36)
	at im.mange.flakeless.innards.FlightDataRecorder.stop(FlightDataRecorder.scala:21)
	at im.mange.flakeless.Flakeless.$anonfun$stopFlight$1(Flakeless.scala:16)
	at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:12)
	at scala.Option.foreach(Option.scala:257)
	at im.mange.flakeless.Flakeless.stopFlight(Flakeless.scala:16)
	at [snip].BrowserTestSuite.testInBrowser(BrowserTestSuite.scala:19)
```

Where

```scala
abstract class BrowserTestSuite extends MyTestSuite {
  def testInBrowser(testBody: SystemUnderTest => Unit): Unit = {
    val sut = PooledServer.acquire

    try {
      sut.flakeless.startFlight(suite, currentTestName)
      sut.reset()
      testBody(sut)
    } catch {
      case t: Throwable =>
        sut.reportFailure(t)
        throw t
    } finally {
      sut.flakeless.stopFlight()
      PooledServer.release(sut)
    }
  }
}
```

**Comment by alltonp** [comment]
That's odd. So it's this line which is causing the exception:

```
sut.flakeless.stopFlight()
```

Which suggests to that the flight recorder was not started for that test, i.e. something when wrong and we didn't get past this line:

```
sut.flakeless.startFlight(suite, currentTestName)
```

Using debugger/println technology, can you confirm that it got past .startFlight() ?

**Comment by tobyweston** [comment]
I suspect #6 is the cause... I missed the cause stacktrace as it happens on the shutdown hook and not at the call site... maybe

**Comment by tobyweston** [comment]
Workaround in #6 fixes this for us, so I'll close this issue
